# Generated by Django 2.0 on 2019-02-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20181223_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tokenitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
