# Generated by Django 2.0 on 2019-02-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190206_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='price',
        ),
    ]
