# Generated by Django 2.0 on 2019-02-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_ordereditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemDesc',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
