# Generated by Django 2.0 on 2019-02-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20190206_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='itemDesc',
        ),
    ]
