# Generated by Django 2.0 on 2019-02-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_menu_itemdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='itemDesc',
        ),
    ]
