# Generated by Django 2.0 on 2019-02-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20190206_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemName',
            field=models.CharField(default='20 characters only .', max_length=20),
        ),
    ]
