# Generated by Django 2.0 on 2019-02-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20190207_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='itemName',
        ),
    ]
