# Generated by Django 2.0 on 2019-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_menu_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='itemName',
            field=models.CharField(default='20 characters only .', max_length=20),
        ),
    ]
