# Generated by Django 2.0 on 2019-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_menu_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
