# Generated by Django 2.0 on 2019-02-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='gst',
        ),
    ]
